# Generated by Django 5.0.4 on 2024-04-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_country_alter_product_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_available',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
