# Generated by Django 5.0.4 on 2024-04-24 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_quantity_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity_available',
        ),
    ]
