# Generated by Django 5.0.4 on 2024-04-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_product_quantity_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
