# Generated by Django 5.0.4 on 2024-05-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Новый', 'Новый'), ('Отменён', 'Отменен'), ('Подтверждён', 'Подтвержден')], default='Новый', max_length=20),
        ),
    ]
