# Generated by Django 5.0.4 on 2024-05-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='massage',
            field=models.CharField(default='Примечание', max_length=500),
        ),
    ]
